### ISSUE TITLE
Bad gateway or 404 not found when changing db password

### ISSUE THREAD

**Issue by deluxejuice** [solidnerd/docker-bookstack#122]
When I change the mysql password from secret to something else the container starts but I get a bad gateway error or a 404 not found.

```
  mysql:
    image: mysql:5.7.21
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal

  bookstack:
    image: solidnerd/bookstack:latest
    depends_on:
      - mysql
    networks:
      - internal
      - web
    environment:
      - DB_HOST=mysql:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=secret
    volumes:
      - uploads:/var/www/bookstack/public/uploads
      - storage-uploads:/var/www/bookstack/public/storage
    ports:
      - "8080:80"
```

Am I supposed to leave those values as secret?
