### ISSUE TITLE
Uploaded Pictures, Profile Pictures etc. doesn't persist on host

### ISSUE THREAD

**Issue by Piket95** [solidnerd/docker-bookstack#167]
Hello,

i experienced the problem, that when im uploading a profile picture or any other picture for a book page the picture only live as long as the container isn't stopped or removed.

In the .env config-file i changed the "STORAGE_TYPE" value to "local_secure". The pictures now are saved in the storage folder in the container. But on my host the files doesn't appear in the storage folder. That one keeps empty.

Files found in container:
`root@e347554fce14:/var/www/bookstack# find ./ -name "80006E31.gif"
./storage/uploads/images/gallery/2019-11/thumbs-150-150/80006E31.gif
./storage/uploads/images/gallery/2019-11/80006E31.gif`

Files also should be in storage on the host system but they aren't:
`root@linuxtest:/var/lib/docker/volumes/docker_bookstack/_data/storage/uploads/images# ls -al
total 12
drwxrwxr-x 2 www-data www-data 4096 Nov 15 03:11 .
drwxrwxr-x 4 www-data www-data 4096 Nov 15 03:11 ..
-rwxrwxr-x 1 www-data www-data   14 Okt 16 15:35 .gitignore`

My docker-compose.yaml looks like this:

```yaml
version: '3.7'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: bookstack
    volumes:
      - $HOME/docker/volumes/mariadb/data:/var/lib/mysql
      
  wiki:
    image: solidnerd/bookstack
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb:3306
      DB_DATABASE: bookstack
      DB_USERNAME: root
      DB_PASSWORD: toor
    volumes:
      - bookstack:/var/www/bookstack

volumes:
  bookstack:
```

I hope somebody have an idea how to solve this problem. Because I have been sitting on this problem for 2 or 3 days now ^^'

Greetings
Piket95
