### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by azN2** [solidnerd/docker-bookstack#20]
Hey, I'm trying to configure my docker-compose.yml to work with Let's Encrypt. 
```
      jrcs/letsencrypt-nginx-proxy-companion
      jwilder/nginx-proxy 
```
are the images I'm using to handle the process automatically. 
typically with this command added to the docker-compose.yml file added in the environment section
```
- VIRTUAL_HOST=wiki.foo.bar
- LETSENCRYPT_HOST=wiki.foo.bar
- LETSENCRYPT_EMAIL=no@email.com
```
docker-compose.yml
```
version: '2'
services:

  mysql:
    image: mysql:5.7.12
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - ./mysql:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:0.14.3
    depends_on:
    - mysql
    environment:
    - VIRTUAL_HOST=wiki.foo.bar
    - LETSENCRYPT_HOST=wiki.foo.bar
    - LETSENCRYPT_EMAIL=no@email.com
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    volumes:
    - ./uploads:/var/www/BookStack/public/uploads
    - ./storage-uploads:/var/www/BookStack/storage/uploads
    ports:
    - "8080:80"
```
This isn't working. I've tried to do this with individual containers as well with no luck.  
Thanks for any help.
