### ISSUE TITLE
Accessing container via NGINX proxy doesn't load CSS

### ISSUE THREAD

**Issue by SteveDinn** [solidnerd/docker-bookstack#205]
I have the container running on a local server running the latest docker on Ubuntu 16.04. When I accessed the container's exposed port directly, everything worked fine. But when accessing via the NGINX proxied URL, the CSS does not load. I can't even see a request in the log.

I then tried adding the APP_URLn environment variable, this causes the container's direct URL to redirect to the proxied URL, but the CSS still does not load.

The "base-url" meta property is set correctly:
```
<meta name="base-url" content="https://bookstack.example.com">
```
The URLs for the CSS look good in the HTML:
```
<link rel="stylesheet" href="https://bookstack.example.com/dist/styles.css?version=v0.29.3">
<link rel="stylesheet" media="print" href="https://bookstack.example.com/dist/print-styles.css?version=v0.29.3">
```

Docker-compose YAML:
```
  bookstack:
    container_name: bookstack
    hostname: bookstack
    image: solidnerd/bookstack:0.29.3
    restart: unless-stopped
    environment:
      - APP_URL=https://bookstack.example.com
      - DB_HOST=mysql:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=[redacted]
    ports:
      - 83:8080
```
NGINX site config:
```
server {
    listen *:80;
    server_name bookstack.example.com;
    return 301 https://bookstack.example.com$request_uri;
}

server {
    listen *:443 ssl;

    server_name bookstack.example.com;

    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

    # Ensure this line points to your dhparams file
    ssl_dhparam /etc/nginx/ssl/dhparams.pem;

    # These shouldn't need to be changed
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    proxy_buffering                    off;
    proxy_pass_header                  Authorization;
    proxy_redirect                     http:// https://;
    proxy_http_version                 1.1;
    proxy_set_header Host              $host;
    proxy_set_header Upgrade           $http_upgrade;
    proxy_set_header Connection        $connection_upgrade;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_max_temp_file_size           0;
    client_max_body_size               0;

    location / {
        proxy_pass                         http://10.1.1.4:83$1$is_args$args;
    }
}
```
