### ISSUE TITLE
Blocked on wait-for-db

### ISSUE THREAD

**Issue by alexandre-snr** [solidnerd/docker-bookstack#206]
Hi,

I am trying to run bookstack using this docker image but the bookstack container is blocked on:
`wait-for-db: waiting for db:3306`

Here is my `docker-compose.yml`:
```yaml
version: '3'

services:
    bookstack:
        image: solidnerd/bookstack:0.29.3
        networks: 
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.bookstack-secured.rule=Host(`bookstack.example.com`)"
            - "traefik.http.routers.bookstack-secured.entrypoints=websecure"
            - "traefik.http.routers.bookstack-secured.tls.certresolver=myResolver"
        volumes:
            - uploads:/var/www/bookstack/public/uploads
            - storage-uploads:/var/www/bookstack/storage/uploads
        environment:
            - DB_HOST=db:3306
            - DB_USERNAME=bookstack
            - DB_PASSWORD=bookstack
            - DB_DATABASE=bookstack
        depends_on:
            - db
    db:
        image: mysql:5.7.31
        environment:
            - MYSQL_DATABASE=bookstack
            - MYSQL_USER=bookstack
            - MYSQL_PASSWORD=bookstack
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
    uploads:
    storage-uploads:

networks:
    web:
        external: true
```

Any idea someone?

I can connect to the mysql server. It is up.

Thank you
