### ISSUE TITLE
Email confirmation not able to send

### ISSUE THREAD

**Issue by wiledal** [solidnerd/docker-bookstack#22]
Hey,
Just deployed this with `docker-compose`. Set it up restricted email addressed for registration. Get this error when trying to register. Is it missing a mailer-package?

![Email error](http://i.imgur.com/vZYhIxb.png)

**Comment by predmijat** [comment]
Did you get it to work?
I've added:
```
- MAIL_HOST=smtp.mandrillapp.com
- MAIL_USERNAME=xxx
- MAIL_PASSWORD=yyy
```
in `docker-compose.yml` under `environment` section (PORT is default, 587, so I left it out), but I get the same error.

`docker logs` doesn't provide anything useful as far as I can tell...

edit: `telnet smtp.mandrillapp.com 587` from inside the container works.
edit2: I can send email from inside the container using `ssmtp` and the same parameters I used in `docker-compose.yml`

**Comment by nickzengxl** [comment]
I hit this issue too, did you find how to solve it now? @predmijat

**Comment by predmijat** [comment]
Nope

**Comment by ssddanbrown** [comment]
Just tested mail config via docker-compose and all worked as expected for me.

@predmijat I think the default port when using docker-compose is `1025`. Try setting `MAIL_PORT=587` within your environment to see if that's the issue.

**Comment by nickzengxl** [comment]
I still cannot solve this issue in my bookstack:

This is my docker-compose file:

```
version: '2'
services:
  mysql:
    image: mysql:5.7.21
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - /srv/bookstack/mysql-data:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:0.21.0
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    - MAIL_HOST=smtp.exmail.qq.com
    - MAIL_USERNAME=book-haha@test.com
    - MAIL_PASSWORD=xxxxx
    - MAIL_PORT=465
    - MAIL_FROM=book-haha@test.com
    - MAIL_FROM_NAME=book-haha
    volumes:
    - /srv/bookstack/uploads:/var/www/bookstack/public/uploads
    - /srv/bookstack/storage-uploads:/var/www/bookstack/public/storage
    ports:
    - "8080:80"
```
