### ISSUE TITLE
containers randomly exit with status code 255

### ISSUE THREAD

**Issue by bryanpedini** [solidnerd/docker-bookstack#231]
### Description:
The docker containers shut down themselves with a "generic error" (code 255) within (usually) a day from every manual restart

### Setup:
Debian 10 buster stable `Linux docker 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux`
Docker `Docker version 20.10.3, build 48d30b5`
Docker Compose `docker-compose version 1.26.2, build eefe0d31`

### `docker-compose.yml`:
```
version: '3'

services:
  app:
    image: solidnerd/bookstack:0.30.7
    environment:
      - APP_URL="https://bookstack.bjphoster.com"
      - DB_HOST=db:3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
    volumes:
      - bk_ups:/var/www/bookstack/public/uploads
      - bk_stg:/var/www/bookstack/storage/uploads
    depends_on:
      - db
    ports:
      - ${HTTP_PORT}:8080
  db:
    image: mariadb:10.5.8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  bk_ups:
  bk_stg:
```

### Nginx reverse proxy:
```
server {
    listen 80;
    server_name bookstack.bjphoster.com;
    access_log /dev/null;
    error_log /var/log/nginx/bookstack_error.log;
    include /etc/nginx/snippets/redirect-ssl.conf;
}
server {
    listen 443 ssl;
    ssl_certificate /path/to/fullchain.pem;
    ssl_certificate_key /path/to/privkey.pem;
    server_name bookstack.bjphoster.com;
    access_log /var/log/nginx/bookstack_access.log;
    error_log /var/log/nginx/bookstack_error.log;
    location / {
        proxy_pass http://127.0.0.1:8089;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Url-Scheme $scheme;
    }
}
```

### Expected behavior:
Docker stays up and running unless manually stopped (as per docker-compose definitions)

### Actual behavior:
The docker containers after a short amount of time (usually less than a day) crash for an unexplicable reason and with an unknown generic error (logs: `[mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully`)

### Notes:
- Yes, this is the only one of many services running on my machine that has this problem (unfortunately)
- Thank you very much in advance
