### ISSUE TITLE
BUG: Unable to start container

### ISSUE THREAD

**Issue by Peter1994** [SolidNerd/docker-bookstack#289]
When attempting to start the container on the latest master version (10 hours old) the following error appears:
```
wait-for-db: waiting for mysql:3306
Generating Key...
wait-for-db: done

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/bookstack/app/Config/session.php on line 62

Deprecated: strncmp(): Passing null to parameter #1 ($string1) of type string is deprecated in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 820

In Request.php line 334:
                                                                               
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must  
   be of type string, null given, called in /var/www/bookstack/vendor/laravel  
  /framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php on   
  line 32                                                                      
                                                                               
```
docker-compose.yml:
```yaml

version: '2'
services:
  mysql:
    restart: always
    image: mysql:5.7.33
    environment:
    - MYSQL_ROOT_PASSWORD=<redacted>
    - MYSQL_DATABASE=<redacted>
    - MYSQL_USER=<redacted>
    - MYSQL_PASSWORD=<redacted>
    volumes:
    - /data/storage/bookstack/mysql:/var/lib/mysql

  bookstack:
    restart: always
    image: solidnerd/bookstack:master
    depends_on:
    - mysql
    environment:
    - APP_DEBUG=true
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=<redacted>
    - DB_PASSWORD=<redacted>
    - AUTH_METHOD=ldap
    - LDAP_SERVER=<redacted>
    - LDAP_BASE_DN="<redacted>"
    - LDAP_DN="<redacted>"
    - LDAP_PASS=<redacted>
    - LDAP_USER_FILTER=(&(sAMAccountName=$${user}))
    - LDAP_VERSION=3
    - LDAP_USER_TO_GROUPS=true
    - LDAP_GROUP_ATTRIBUTE="memberOf"
    - LDAP_REMOVE_FROM_GROUPS=true
    - MAIL_DRIVER=smtp
    - MAIL_HOST=<redacted>
    - MAIL_FROM=<redacted>
    - MAIL_FROM_NAME=Bookstack
    - APP_AUTO_LANG_PUBLIC=true
    volumes:
    - /data/storage/bookstack/app/uploads:/var/www/bookstack/public/uploads
    - /data/storage/bookstack/app/storage-uploads:/var/www/bookstack/storage/uploads
    ports:
    - "80:8080"

```
