### ISSUE TITLE
Docker Compose LDAP Issues - Container will not login just times out

### ISSUE THREAD

**Issue by sudo-kraken** [SolidNerd/docker-bookstack#298]
I am trying to setup a new instance of BookStack and I get to the login page, however when you try login it just spins forever and times out, I cant work out where the issue is, I have tried to recreate this but it just does the same, if you remove all the LDAP options it allows you to log in.

I have another non ldap instance working but this one will not work with ldap, it just loads up and then freezes every time you log in.

docker logs bookstack2 - produces this:

```
wait-for-db: waiting for bookstack_db2:3306
wait-for-db: done
Generating Key...
base64:xxxxxxxx
Starting Migration...
Nothing to migrate.
Clearing caches...
Application cache cleared!
Compiled views cleared!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.10.6. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.10.6. Set the 'ServerName' directive globally to suppress this message
[Fri Feb 11 16:01:29.211342 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/8.1.1 configured -- resuming normal operations
[Fri Feb 11 16:01:29.211453 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
bookstack:80 10.0.10.1 - - [11/Feb/2022:16:01:52 +0000] "GET / HTTP/1.1" 302 1821 "http://xx.xx.xx.xx:8080/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/xx.xx.xx.xxSafari/537.36 Edg/xx.xx.xx.xx"
bookstack:80 10.0.10.1 - - [11/Feb/2022:16:01:52 +0000] "GET /login HTTP/1.1" 200 3455 "http://xx.xx.xx.xx:8080/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/xx.xx.xx.xx"
```

Here is my compose yaml, with all sensitive info omitted. 

```
 ################################# Networks #################################

networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24

  default:
    driver: bridge

 ################################# Services #################################

services:

 ############################### Knowledgebase #############################

  bookstack2:
    image: solidnerd/bookstack:21.12.1
    container_name: bookstack2
    networks:
      - app_net
    environment:
      - AUTH_METHOD=ldap
      - DB_HOST=bookstack_db2
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=supersecretpassword
      - APP_URL=http://xx.xx.xx.xx:8080
      - LDAP_SERVER=xx.xx.xx.xx:389
      - LDAP_BASE_DN="OU=company Users,DC=company,DC=local"
      - LDAP_DN=ktbind
      - LDAP_PASS="supersecretpassword"
      - LDAP_USER_FILTER=(&(sAMAccountName=\${user}))
      - LDAP_START_TLS=false
      - LDAP_TLS_INSECURE=true
      - LDAP_AUTO_CONFIRM_EMAIL=true
      - LDAP_EMAIL_ATTRIBUTE=mail
      - LDAP_VERSION=3
      - MAIL_DRIVER=smtp
      - MAIL_HOST=xx.xx.xx.xx
      - MAIL_PORT=465
      - MAIL_ENCRYPTION=tls
      - MAIL_USERNAME=bookstack@company.com
      - MAIL_FROM=bookstack@company.com
      - MAIL_FROM_NAME=BookStack
    volumes:
      - $DOCKERLOCALDIR/bookstack2/uploads:/var/www/bookstack/public/uploads
      - $DOCKERLOCALDIR/bookstack2/storage-uploads:/var/www/bookstack/storage/uploads
    ports:
      - 8080:8080
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - bookstack_db2

  bookstack_db2:
    image: mysql:8.0
    container_name: bookstack_db2
    environment:
    - MYSQL_ROOT_PASSWORD=supersecretpassword
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=supersecretpassword
    volumes:
    - $DOCKERLOCALDIR/bookstackdb2:/var/lib/mysql
    networks:
      - app_net
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

```

Any ideas welcome at this point.
