### ISSUE TITLE
docker compose Active Directory auth 

### ISSUE THREAD

**Issue by skollrc** [SolidNerd/docker-bookstack#376]
Hi everyone, 

I'm trying to use BookStack with ldap auth in a docker container but it actually doesn't work and I don't know why. From the docker container, I can ping the fqdn of the AD server. With debug on I have this issue: 
`ErrorException ldap_bind(): Unable to bind to server: Invalid credentials`

Does any one have succed to use BookStack with AD auth?

Here is my docker compose:

```
version: '2'
services:

  mysql:
    container_name: bookstack-mysql
    restart: unless-stopped
    image: lscr.io/linuxserver/mariadb:latest
    environment:
    - TZ=Europe/Paris
    - MYSQL_ROOT_PASSWORD=YourRootPassw0rd!
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=YourPassw0rd!
    volumes:
    - /docker/config/bookstack/db/mysql:/config
    networks:
      - frontend
  bookstack:
    container_name: bookstack
    restart: unless-stopped
    image: lscr.io/linuxserver/bookstack:latest
    depends_on:
    - mysql
    environment:
    - APP_ENV=production
    - APP_DEBUG=true
    - APP_URL=http://doc.my.domain
    #- WKHTMLTOPDF=
    - DB_HOST=mysql
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=YourPassw0rd!
# General auth
    - AUTH_METHOD=ldap
    - LDAP_SERVER=srvad1.my.domain
    - LDAP_BASE_DN="OU=AAA,DC=my,DC=domain"
    - LDAP_DN="CN=someuser,OU=AAA,OU=BBB,DC=my,DC=domain"
    - LDAP_PASS="someuserpass"
    - LDAP_USER_FILTER=(&(sAMAccountName=$${user}))
    - LDAP_VERSION=3
    - LDAP_START_TLS=false
    - LDAP_ID_ATTRIBUTE=BIN;objectGUID
    volumes:
    - /docker/config/bookstack/conf:/config
    ports:
    - "8084:80"
    networks:
      - backend
      - frontend
networks:
    backend:
      external:
        name: npm_default
    frontend:
```
