### ISSUE TITLE
Latest update Broke the Login Page

### ISSUE THREAD

**Issue by mariushosting** [SolidNerd/docker-bookstack#406]
Latest update 23.06 broke the login page.

Deprecated
: explode(): Passing null to parameter #2 ($string) of type string is deprecated in
/var/www/bookstack/app/Config/saml2.php
on line
17

![deprecated](https://github.com/solidnerd/docker-bookstack/assets/37554361/ac8d844f-a074-4246-9581-3fa72f31cb6e)

**Comment by mariushosting** [comment]
@ssddanbrown @solidnerd 
![broken](https://github.com/solidnerd/docker-bookstack/assets/37554361/66bfd782-56b5-4fd4-9d13-67a68c2a4fcc)

**Comment by ssddanbrown** [comment]
@mariushosting 

- Are you passing in a `.env` file to the container?
- In a passed `.env` file **and/or** via docker env options, do you have any options defined starting with `SAML2_`?

**Comment by mariushosting** [comment]
> @mariushosting
> 
> * Are you passing in a `.env` file to the container?
> * In a passed `.env` file **and/or** via docker env options, do you have any options defined starting with `SAML2_`?

Never used this option in the env file v23.05.2
Should I have to add a new environment?

**Comment by mariushosting** [comment]
I just want to mention this is a fresh installation.

No issue with this version: https://github.com/solidnerd/docker-bookstack/releases/tag/23.5.2

The issue started with this version: https://github.com/solidnerd/docker-bookstack/releases/tag/23.6.0

My compose is here at STEP 20: https://mariushosting.com/how-to-install-bookstack-on-your-synology-nas/
No SAML2_ environment.

**Comment by rjhenry** [comment]
I've got the same with my Kubernetes hosted installation. Environment as follows:
```yaml
# Configure DB settings:
- name: DB_HOST
  # Service exposed in-cluster
  value: mariadb
- name: DB_DATABASE
  value: bookstack
- name: DB_USERNAME
  value: bookstack
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: mysql-database-credentials
      key: mariadb-password
- name: APP_KEY
  value: <redacted>
# Where the app is expected to run, no trailing slash
- name: APP_URL
  value: https://bookstack.rickhenry.uk
- name: STORAGE_TYPE
  value: s3
- name: STORAGE_S3_KEY
  valueFrom:
    secretKeyRef:
      name: bookstack-minio-credentials
      key: access-key
- name: STORAGE_S3_SECRET
  valueFrom:
    secretKeyRef:
      name: bookstack-minio-credentials
      key: secret-key
- name: STORAGE_S3_BUCKET
  value: <redacted>
- name: STORAGE_S3_REGION
  value: irrelevant_in_minio
- name: STORAGE_S3_ENDPOINT
  value: <redacted>
- name: STORAGE_URL
  value: >-
    <redacted>
# Configure OIDC
- name: AUTH_METHOD
  value: oidc
# Automagically log in with OIDC instead of requiring a clicky button
- name: AUTH_AUTO_INITIATE
  value: "true"
# Only used in display
- name: OIDC_NAME
  value: Keycloak
- name: OIDC_CLIENT_ID
  value: bookstack
- name: OIDC_CLIENT_SECRET
  valueFrom:
    secretKeyRef:
      name: sso-credentials
      key: sso-password
- name: OIDC_ISSUER
  value: <redacted, hosted Keycloak instance>
# Autodiscover URLs for issuer. Requires
# ${OIDC_ISSUER}/.well-known/openid-configuration to exist and return
# usable JSON
- name: OIDC_ISSUER_DISCOVER
  value: "true"
# Groups are allocated from Keycloak's client roles
- name: OIDC_GROUPS_CLAIM
  value: "resource_access.bookstack.roles"
- name: OIDC_USER_TO_GROUPS
  value: "true"
- name: OIDC_REMOVE_FROM_GROUPS
  value: "true"
```

No `SAML2_` environment variables set, but I _am_ using OAuth2.

Checking in the running pod shows nothing SAML-y in the environment (as in `env` output) and all SAML-y values in the `.env` file show either `null` or `false`.

```
      # SAML2 Settings; AUTH_MODE=saml2
      SAML2_NAME=null
      SAML2_EMAIL_ATTRIBUTE=null
      SAML2_EXTERNAL_ID_ATTRIBUTE=null
      SAML2_USER_TO_GROUPS=false
      SAML2_GROUP_ATTRIBUTE=null
      SAML2_DISPLAY_NAME_ATTRIBUTES=null
      SAML2_IDP_ENTITYID=null
      SAML2_AUTOLOAD_METADATA=false
      SAML2_IDP_SSO=null
      SAML2_IDP_SLO=null
      SAML2_IDP_x509=null
      SAML2_IDP_AUTHNCONTEXT=false
      SAML2_SP_x509=null
      SAML2_SP_x509_KEY=null
      SAML2_DUMP_USER_DETAILS=false
      SAML2_ONELOGIN_OVERRIDES=null
      SAML2_REMOVE_FROM_GROUPS=false
```

There's nothing in the stdout logs, and the `storage/logs/` directory is empty - I'll see if I can get some debug logs from there.
