### ISSUE TITLE
Multi arch images?

### ISSUE THREAD

**Issue by skymoore** [SolidNerd/docker-bookstack#424]
I want to set up and PR building multi-arch images in the github workflows for this repo.  I'm running bookstack using this image in an arm based kubernetes cluster and currently I build the images manually.  I've tried working around this validation step:

```
e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: image-bookstack-master
        path: /tmp

    - name: Load Docker image
      run: |
        docker load --input /tmp/image-bookstack.tar
        docker image ls -a
```
It seems that the docker build push action can output an oci multi-arch image tarball, but docker cannot load or import it.  So rewrote this step with containerd and things started to get complicated.  Ultimately I think, why does this repo need this?  So can someone please explain why there is this three step process for building the image where the verification step is to see if docker can load an image that docker built.  Has there been an issue with loading images built in the past?  I don't understand why this needs to be done.  If we eliminate this e2e job, multi-arch images become easy.
