### ISSUE TITLE
Missing Link in docker-compose.yml

### ISSUE THREAD

**Issue by Zwiebaechcken** [SolidNerd/docker-bookstack#484]
Hello!
I was just messing around with bookstack and had problems deploying it. 
As it turned out there is a missing link for bookstack to mysql in the docker-compose.yml.

Here's how I got it working:

```yaml
version: '2'
services:
  mysql:
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=###
      - MYSQL_DATABASE=bookstackdb
      - MYSQL_USER=bookstackuser
      - MYSQL_PASSWORD=####
    volumes:
      - mysql-data:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:24.2.3-1
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql:3306
      - DB_DATABASE=bookstackdb
      - DB_USERNAME=bookstackuser
      - DB_PASSWORD=###
      - APP_URL=http://localhost:8080
      - APP_KEY=###
    volumes:
      - uploads:/var/www/bookstack/public/uploads
      - storage-uploads:/var/www/bookstack/storage/uploads
    ports:
      - "8080:8080"
   #Here is what I added
    links:
      - mysql

volumes:
  mysql-data:
  uploads:
  storage-uploads:
```
