### ISSUE TITLE
port to AWS (RDS Database)

### ISSUE THREAD

**Issue by jacksonp2008** [solidnerd/docker-bookstack#50]
Maybe it's obvious but I'm fairly new to docker.  Attempt to change database to point to RDS and I get 

```
bookstack_1  |   SQLSTATE[HY000] [1049] Unknown database 'bookstack' (SQL: select * from inf  
bookstack_1  |   ormation_schema.tables where table_schema = bookstack and table_name = migr  
bookstack_1  |   ations)                                                                                                                   
bookstack_1  |   [PDOException]                                       
bookstack_1  |   SQLSTATE[HY000] [1049] Unknown database 'bookstack'  
                                                    
```
The database would not be created in this case, is there something I should run to create it?

Here is my docker-compose.yml

```
  bookstack:
    image: solidnerd/bookstack:0.17.1
    environment:
    - DB_HOST=sdfsdfsdf.cccssdfsfsdfsdf.us-east-1.rds.amazonaws.com:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=someuser
    - DB_PASSWORD=secretpassword
    volumes:
    - uploads:/var/www/BookStack/public/uploads
    - storage-uploads:/var/www/BookStack/storage/uploads
    ports:
    - "8080:80"
```
