### ISSUE TITLE
Docker using .env?

### ISSUE THREAD

**Issue by jacksonp2008** [solidnerd/docker-bookstack#51]
I am converting to the docker image hosting on AWS.   I put the .env file in the same directory with docker-compose.yml etc.  it contains LDAP settings but I do not see any packets going to my LDAP server.  It appears that it may not be reading .env, do I have this in the wrong location?

thanks!

**Comment by ssddanbrown** [comment]
@jacksonp2008 

When using docker-compose, variables in a `.env` will not be passed through to the container, They are only usable within the docker-compose itself.

You [should be able to use](https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option) the `env_file` option to pass them through to the container like so:

```yaml
version: '2'
services:

  mysql:
    image: mysql:5.7.12
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - mysql-data:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:0.17.1
    depends_on:
    - mysql
    env_file: .env
    volumes:
    - uploads:/var/www/BookStack/public/uploads
    - storage-uploads:/var/www/BookStack/storage/uploads
    ports:
    - "8080:80"
```
