### ISSUE TITLE
third party auth

### ISSUE THREAD

**Issue by flemming-pr** [solidnerd/docker-bookstack#76]
How can I activate github auth like in the main docu shown?

**Comment by ssddanbrown** [comment]
@flemssound Instead of updating a `.env` file you just need to set any variables on the container environment instead.

For example, If you're using docker-compose you config will look something like this:

```yml
version: '2'
services:
  mysql:
    image: mysql:5.7.21
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - mysql-data:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:0.20.3
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    - GITHUB_APP_ID=xxxxxxxxxxxxxxx
    - GITHUB_APP_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - APP_URL=http://localhost:8080
    volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage-uploads:/var/www/bookstack/public/storage
    ports:
    - "8080:80"

volumes:
 mysql-data:
 uploads:
 storage-uploads:
```
