### ISSUE TITLE
Container behind load balancer sending back http prefix rather than https

### ISSUE THREAD

**Issue by forescout-spollock** [solidnerd/docker-bookstack#84]
Using OKTA login, sitting behind a load balancer that is listening on 443 and forwarding to 8080 for the container.  When the user logs in with OKTA at **https**://dev-wiki.fsu.com/login, they are redirected to **http:**//dev-wiki.fsu.com/ which is not a valid site.  However, it did indeed log them in with OKTA and a refresh of **https**://dev-wiki.fsu.com/ leaves everything working as expected.

Another data point: I pointed the load balancer at the same version of bookstack, only installed on a local machine rather than the container and it works fine. This config uses identical OKTA settings as well as an identical .env file.  One difference is that the local version is running on 443.

Perhaps apache2 in the container needs some kind of rewrite rules.  I did attach to the container directly and modify /etc/apache2/sites-enabled# cat bookstack.conf 

and added

     RewriteEngine on 
     RewriteCond %{HTTP:X-Forwarded-Proto} !https 
     RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

But it did not seem to help.

Any ideas are most appreciated,
Thanks

**Comment by forescout-spollock** [comment]
Hi Dan, 



it's set in the .env file, same directory as docker-compose.yml

```

# The below url has to be set if using social auth options

# or if you are not using BookStack at the root path of your domain.

APP_URL=https://dev-wiki.fsu.com​

```

and my docker-compose.yml 

```
version: '2'
services:
 bookstack:
    image: solidnerd/bookstack:0.21.0
    restart: always
    environment:
    - DB_HOST=dsdfsdfsdf.cccskphrgnlg.us-xxx-1.rds.amazonaws.com:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=secretuser
    - DB_PASSWORD=secretpassword
    env_file: .env
    volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage-uploads:/var/www/bookstack/public/storage
    ports:
    - "8080:80"

volumes:
 uploads:
 storage-uploads:
```
