### ISSUE TITLE
How to use LDAP authentication?

### ISSUE THREAD

**Issue by imaoxian** [solidnerd/docker-bookstack#94]
When I log in using "admin@domain.com" and the password "admin", I am prompted: "An unknown error occurred". How can I solve it?

This is my docker-compose.yml file.
```
version: '2'
services:
  mysql:
    image: mysql:5.7.21
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - /data/bookstack/mysql-data:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:0.22.0
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    - AUTH_METHOD=ldap
    - LDAP_SERVER=192.168.10.10:389
    - LDAP_BASE_DN=ou=domain.com,dc=domain,dc=com
    - LDAP_USER_FILTER=(&(uid=$${user}))
    - LDAP_DN=cn=admin,dc=domain,dc=com
    - LDAP_PASS=admin
    volumes:
    - /data/bookstack/uploads:/var/www/bookstack/public/uploads
    - /data/bookstack/storage-uploads:/var/www/bookstack/public/storage
    ports:
    - "8080:80"
```
